### PR TITLE
Project Alpha - 6/3 PR's

### PR DESCRIPTION
**Pull request by rovertdude**
This includes all Project Alpha approved pull requests.

### CODE REVIEW

**Comment by rovertdude** [comment]
Added Founder and DFM developer tagging.
This counts as 1 edit.

**Comment by adroition** [comment]
@PuggyCrew updated the Muter.java file which was accepted.
This patched the problem where muted people can message people.

**Comment by PuggyCrew** [comment]
Advertisements and credits have been enforced in this edit I have made.

**Comment by PuggyCrew** [comment]
We are at 3 edits. Minimum is 5.

**Comment by rovertdude** [comment]
5/3 pull requests, project is ready to merge.

**Review by adroition — APPROVED** [review]

**Review by PuggyCrew — APPROVED** [review]

**Comment by rovertdude** [comment]
goodbye project alpha, one last update will be made :)

**Pull request merged**
