### PR TITLE
Project B

### PR DESCRIPTION
**Pull request by adroition**
This is the official pull request for Project B.
Project B's managers are adroition and PuggyCrew.

### CODE REVIEW

**Comment by adroition** [comment]
Project added a fix to /developfreedommod

**Review by rovertdude — APPROVED** [review]
DevelopFreedomMod cmd fix is approved.
Awaiting rest of PR.

**Comment by adroition** [comment]
Project added a few more blocked tags in /tag

**Review by PuggyCrew — CHANGES_REQUESTED** [review]
All good but change the forbidden words as go:
Remove administrator
Remove staff
Remove mod

**Comment by adroition** [comment]
@PuggyCrew Resolved

**Review by PuggyCrew — APPROVED** [review]
Looks all fine so far!

**Review by PuggyCrew — APPROVED** [review]
This is actually well done.
- Legendaria -

**Comment by PuggyCrew** [comment]
Deleted FrontDoor.java

**Comment by PuggyCrew** [comment]
Project is officially finished and frozen.
Needs approval from @adroition me and @rovertdude 

I officially give my approval.

**Comment by adroition** [comment]
I officially give my approval.
@rovertdude

**Review by rovertdude — APPROVED** [review]
I approve of this.
This will be version 1.4

**Pull request merged**
