### PR TITLE
Update Command_toggle.java

### LINKED ISSUE #35: /toggle glitch is back
#24 is back

### PR DESCRIPTION
**Pull request by PuggyCrew**
Fixes #35

### CODE REVIEW

**Review by rovertdude — DISMISSED** [review]

**Review by adroition — DISMISSED** [review]
ignore

**Review by adroition — APPROVED** [review]
approved on behalf of peztez and the dev team -adroition

**Comment by rovertdude** [comment]
t

**Review by rovertdude — APPROVED** [review]
approving on behalf of the dev team

**Comment by adroition** [comment]
ready to merge

**Pull request merged**
