### PR TITLE
Project Omega - 5/4

### PR DESCRIPTION
**Pull request by rovertdude**
This is Project Omega's Pull Request which is on hold.
Manager:
@PuggyCrew

### CODE REVIEW

**Comment by PuggyCrew** [comment]
I'll be the Project Omega manager if you wish

**Comment by rovertdude** [comment]
@PuggyCrew ok

**Comment by PuggyCrew** [comment]
Added /control by suggestion of @adroition

**Comment by rovertdude** [comment]
Needs 2/3 for an early merge. I give my vote.

**Review by PuggyCrew — DISMISSED** [review]
Sorry rovert, but I think we should wait for at least 4
This review has been dismissed by adroition

**Review by adroition — APPROVED** [review]

**Comment by rovertdude** [comment]
Ready to merge, needs @PuggyCrew's approval

**Review by PuggyCrew — APPROVED** [review]

**Pull request merged**
